name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

env:
  TOKENZ: ${{ secrets.TOKENZ }}

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      # - run: |
      #     go run *.go \
      #       --token ${{ secrets.TOKENZ }} \
      #       --preset indonesia \
      #       --amount 2000 \
      #       --consider 2000 \
      #       --output json \
      #       --file ./data
      - run: ls -al

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node code.js

      - run: ls -al
      
      - name: push generated file
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > indo.txt
          git config --global user.name 'Depa Panjie Purnama'
          git config --global user.email 'depapp@users.noreply.github.com'
          ls -al
          git pull
          ls -al
          git add indo.txt
          git commit -am "update data indo $d"
          git push

      - name: Upload data.json as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: ./indogithubers.json