name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 13 */1 * *'

permissions:
  contents: write

env:
  TOKENZ: ${{ secrets.TOKENZ }}

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - run: |
          go run *.go \
            --token ${{ secrets.TOKENZ }} \
            --preset indonesia \
            --amount 7000 \
            --consider 7000 \
            --output json \
            --file ./data
      - run: ls -al

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node code.js

      - run: ls -al
      
      - name: push generated file
        run: |
          d=$(date +"%Y-%m-%d-%H-%M")
          git config --global user.name 'Depa Panjie Purnama'
          git config --global user.email 'depapp@users.noreply.github.com'
          git fetch --all
          git reset --hard origin/master
          git pull
          ls -al
          git add indogithubers.json
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -am "update indogithubers data - $d"
            git push
          fi
