name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TOKENZ: ${{ secrets.TOKENZ }}

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - run: |
          go run *.go \
            --token ${{ secrets.TOKENZ }} \
            --preset indonesia \
            --amount 2000 \
            --consider 2000 \
            --output json \
            --file ./data
      - run: ls -al

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node code.js

      - run: ls -al

      - name: Configure Git
        run: |
          git config --local user.email "depa.article@gmail.com"
          git config --local user.name "depapp"
      
      - name: Add and Commit Files
        run: |
          current_date=$(date +"%Y-%m-%d")
          git add indogithubers.json
          git commit -m "update indogithubers data - $current_date"
      
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload data.json as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: ./indogithubers.json