name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TOKENZ: ${{ secrets.TOKENZ }}

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - run: |
          go run *.go \
            --token ${{ secrets.TOKENZ }} \
            --preset indonesia \
            --amount 10 \
            --consider 10 \
            --output json \
            --file ./data
      - run: ls -al
      - name: Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node code.js
      - run: ls -al
      - name: Upload data.json as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: ./*-indogithubers.json